include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    one_member_abstracts: false
    public_member_api_docs: false
    omit_local_variable_types: false
    avoid_catches_without_on_clauses: false
    use_setters_to_change_properties: false
    avoid_function_literals_in_foreach_calls: false